version: '3'

services:
  myapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "3000"
    env_file:
      - .env
    ports: 
      - "3000:3000"